name: grocery_mart_must_company_flutter_assesement
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.7
  provider: ^6.0.0
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
